version: "1.0"
transport:
  http:
    addr: ':8080'
    tls:
      certFile: ''
      keyFile: ''

providers:
  - provider: smtp
    code: GmailNoReply
    params:
      host: smtp.gmail.com
      port: 587
      username: 'env APP_GMAIL_NO_REPLY_USERNAME'
      password: 'env APP_GMAIL_NO_REPLY_PASSWORD'
  - provider: TG
    code: TG_BOT
    params:
      token: 'env APP_TG_BOT_TOKEN'

templates:
  - code: test_message_string
    from: "test@test.com"
    to:
      - "romanov.i.u@yandex.ru"
    subject: "test email"
    body:
      text: |
        ### Heading
        
        * {{.first}}
        * {{.second}}
  - code: test_message_template
    to:
      - "romanov.i.u@yandex.ru"
    subject: "test email"
    body:
      path: "./resource/emails/test/test_message_template.html"
